"""A setting written in a config file has to reach the code, or be listed here.

Three silent deaths, found 2026-08-16 by auditing a real workspace instead of
reading the loader:

    unmapped   the key is not in the key map, so it never enters `raw`
    dropped    it enters `raw` and the namespace constructor never names it, so
               `P` has no such attribute and every `getattr(P, name, default)`
               downstream takes the literal
    unread     it reaches `P` and no module reads it

`dropped` is the one that cost accuracy. `instrument.telescope_focal_mm` and
`camera_pixel_um` were mapped and never named, so `InstrumentConfig` fell back
to 3947 mm and 3.76 um — the CDK500 with a C3-61000 — for every instrument. The
five paper clusters *are* that instrument, so they were right by coincidence;
the QHY600 workspace would have run at 0.197 "/px instead of 0.740 and the
Sinistro at 0.197 instead of 0.389. Headless runs take `match.pixel_scale_arcsec`
straight from the file and were never affected, so no stored product is wrong —
only the GUI, which builds an `InstrumentConfig` and overwrote the correct value
with the default one.

The pinned lists below are not a target of zero. Most of what remains is
vestigial and removing it is its own job. They exist so the number cannot grow
without someone writing down why.
"""

from __future__ import annotations

import json

import pytest

from apex.config.config_audit import audit, dropped_settings
from apex.config.parameters_cmd import read_params

# Settings that vanish between the key map and the namespace. Generated by
# building a config that sets every mapped key, so the list is complete and
# deterministic rather than whatever one workspace happened to contain.
CMD_DROPPED = {
    # Aperture-correction scale *optimiser*: the search was never implemented,
    # only the fixed small/large pair it would have searched between.
    "apcorr_large_scale_max", "apcorr_large_scale_min", "apcorr_max_pairs",
    "apcorr_min_gap_fwhm", "apcorr_optimize_scales", "apcorr_small_scale_max",
    "apcorr_small_scale_min",
    # Master catalogue: the code sizes it with `ref_cat_max_sources` instead.
    "N_master", "master_filter_keep", "master_flux_quantile",
    "master_iso_min_sep_pix", "master_keep_max",
    # Step 10 colour terms.
    "color_clip_sigma", "color_fit_iters", "color_slope_absmax",
    # Frame QC gate.
    "gate_nsrc_min", "gate_sky_sigma_max_e", "keep_positions_if_qc_fail",
    # Legacy duplicates of keys that do arrive: target.ra_deg lands on
    # `target_ra_deg`, which is what the code reads.
    "ra_deg", "dec_deg",
    # Miscellaneous vestiges.
    "clip_max_adu", "clip_min_adu", "cmd_max_sources", "night_gap_hours",
    "save_src2ref_tforms", "ui_canvas_px", "wcs_match_radius_arcsec",
}

LC_DROPPED = {
    "N_master", "apcorr_scale_max", "apcorr_scale_min", "bkg2d_downsample",
    "bkg2d_enable", "clip_max_adu", "clip_min_adu", "dec_deg",
    "detect_keep_max", "gate_nsrc_min", "gate_sky_sigma_max_e",
    "idmatch_use_qc_pass_only", "idmatch_use_wcs_qc_gate",
    "idmatch_wcs_qc_max_p99_px", "idmatch_wcs_qc_max_rms_px",
    "idmatch_wcs_qc_min_inlier_rate", "idmatch_wcs_qc_min_match_n",
    "idmatch_wcs_qc_min_match_rate", "keep_positions_if_qc_fail",
    "master_filter_keep", "master_flux_quantile", "master_iso_min_sep_pix",
    "master_keep_max", "night_gap_hours", "phot_use_original_frames",
    "psf_final_pass_max_iter", "psf_forced_position_lock",
    "psf_grouper_budget_cap", "psf_grouper_budget_frac", "psf_interp_order",
    "psf_profile_error_frac", "ra_deg", "ref_master_union",
    "ref_union_min_frames", "save_src2ref_tforms", "ui_canvas_px",
    "wcs_match_radius_arcsec", "wcs_qc_clip_sigma",
    "wcs_qc_match_radius_arcsec", "wcs_qc_max_center_offset_arcsec",
    "wcs_qc_max_edge_ratio", "wcs_qc_max_p99_px", "wcs_qc_max_rms_px",
    "wcs_qc_min_inlier_rate", "wcs_qc_min_match_n", "wcs_qc_min_match_rate",
    "wcs_qc_require_wcs_ok",
}

# A workspace with the sections a real cluster run touches, written out rather
# than pointed at E:\ so the test runs anywhere.
WORKSPACE = {
    "io": {"result_dir": ".", "data_dir": "."},
    "instrument": {
        "telescope_focal_mm": 1048.0,
        "camera_pixel_um": 3.76,
        "binning": 1,
        "gain_e_per_adu": 0.689,
        "rdnoise_e": 2.1,
    },
    "photometry": {
        "apcorr": {"small_scale": 0.8, "large_scale": 2.4},
        "radii": {"sigma_clip": 3.0, "max_iter": 5},
    },
}


def _config_setting_every_mapped_key(key_map) -> dict:
    """A config that names every key the map knows, so nothing hides."""
    cfg = {"io": {"result_dir": ".", "data_dir": "."}}
    for path, _ in key_map:
        path = tuple(path)
        node = cfg
        for part in path[:-1]:
            node = node.setdefault(part, {})
            if not isinstance(node, dict):
                break
        else:
            node.setdefault(path[-1], 1)
    return cfg


@pytest.fixture
def workspace(tmp_path):
    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(WORKSPACE), encoding="utf-8")
    return config


def test_the_instrument_geometry_arrives(workspace):
    """The pixel scale is derived from these two, so they have to be on `P`."""
    P = read_params(workspace).P
    assert P.telescope_focal_mm == pytest.approx(1048.0)
    assert P.camera_pixel_um == pytest.approx(3.76)


def test_the_pixel_scale_follows_the_configured_optics(workspace):
    """The defect itself: a non-default telescope must not land on the default
    plate scale. 206.265 * 3.76 / 1048 = 0.740 "/px, not 0.197."""
    from apex.core.instrument import InstrumentConfig

    params = read_params(workspace)
    assert InstrumentConfig(params).pix_scale_bin == pytest.approx(0.740, abs=1e-3)


def test_the_aperture_scales_arrive(workspace):
    P = read_params(workspace).P
    assert P.apcorr_small_scale == pytest.approx(0.8)
    assert P.apcorr_large_scale == pytest.approx(2.4)


def test_a_workspace_of_real_settings_loses_nothing(workspace):
    assert dropped_settings(read_params(workspace).P) == []


@pytest.mark.parametrize("mode,pinned", [("cmd", CMD_DROPPED), ("lc", LC_DROPPED)])
def test_the_set_of_settings_that_go_nowhere_is_the_pinned_one(mode, pinned, tmp_path):
    """Set every mapped key and check exactly which ones fail to arrive.

    A name appearing here that is not pinned is a new silent setting: add the
    keyword to the namespace constructor, or drop the key from the map if it is
    really dead — and either way say which in `docs/audit/CONFIG_REACHABILITY.md`.
    """
    if mode == "lc":
        from apex.config.parameters_lc import TOML_KEY_MAP, read_params as read
    else:
        from apex.config.parameters_cmd import TOML_KEY_MAP, read_params as read

    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(_config_setting_every_mapped_key(TOML_KEY_MAP)),
                      encoding="utf-8")
    lost = set(dropped_settings(read(config).P))
    assert not (lost - pinned), f"새로 사라지는 설정: {sorted(lost - pinned)}"
    assert not (pinned - lost), f"이제 도착한다 — 목록에서 지울 것: {sorted(pinned - lost)}"


def test_the_step7_cache_notices_an_aperture_change(tmp_path):
    """The signature listed `forced_r_ap_scale`, a name nothing set, so every
    run hashed None for it and a changed aperture reused the old cache."""
    import re
    from pathlib import Path

    source = (Path(__file__).absolute().parents[1]
              / "apex/gui/workflow/step7_forced_aperture_phot.py").read_text(encoding="utf-8")
    block = source[source.index("_FORCED_SIGNATURE_PARAMS = ("):]
    block = block[:block.index("\n)")]
    names = re.findall(r'"([a-z_0-9]+)"', block)
    assert "apcorr_small_scale" in names
    assert "apcorr_large_scale" in names
    assert "annulus_sigma_clip" in names
    assert "fitsky_max_iter" in names

    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(WORKSPACE), encoding="utf-8")
    P = read_params(config).P
    # `ref_cat_*` are defined in LC only; nothing sets them, so they cannot go
    # stale, but they are the remaining hole in this signature.
    absent = [n for n in names if not hasattr(P, n)]
    assert all(n.startswith("ref_cat_") for n in absent), absent


def test_the_audit_reports_both_kinds(workspace):
    result = audit(workspace)
    assert set(result) == {"unmapped", "dropped"}
    assert not [name for name in result["unmapped"] if name.startswith("photometry.")]


def test_turning_the_aperture_correction_off_does_something(workspace):
    """`photometry.apcorr.apply` reached `P` and nothing read it — Step 7
    multiplied by apcorr unconditionally. Every workspace has it true, so
    wiring it changed no stored product, but the switch has to work."""
    from pathlib import Path

    P = read_params(workspace).P
    assert P.apcorr_apply is True

    source = (Path(__file__).absolute().parents[1]
              / "apex/analysis/forced_photometry.py").read_text(encoding="utf-8")
    assert 'getattr(P, "apcorr_apply"' in source
    assert "if apcorr_apply and n_gc_stars >= apcorr_min_n:" in source

    signature = (Path(__file__).absolute().parents[1]
                 / "apex/gui/workflow/step7_forced_aperture_phot.py").read_text(encoding="utf-8")
    block = signature[signature.index("_FORCED_SIGNATURE_PARAMS = ("):]
    assert '"apcorr_apply"' in block[:block.index("\n)")]
