"""A setting written in a config file has to reach the code, or be listed here.

Three silent deaths, found 2026-08-16 by auditing a real workspace instead of
reading the loader:

    unmapped   the key is not in the key map, so it never enters `raw`
    dropped    it enters `raw` and the namespace constructor never names it, so
               `P` has no such attribute and every `getattr(P, name, default)`
               downstream takes the literal
    unread     it reaches `P` and no module reads it

`dropped` is the one that cost accuracy. `instrument.telescope_focal_mm` and
`camera_pixel_um` were mapped and never named, so `InstrumentConfig` fell back
to 3947 mm and 3.76 um — the CDK500 with a C3-61000 — for every instrument. The
five paper clusters *are* that instrument, so they were right by coincidence;
the QHY600 workspace would have run at 0.197 "/px instead of 0.740 and the
Sinistro at 0.197 instead of 0.389. Headless runs take `match.pixel_scale_arcsec`
straight from the file and were never affected, so no stored product is wrong —
only the GUI, which builds an `InstrumentConfig` and overwrote the correct value
with the default one.

The pinned lists below are not a target of zero. Most of what remains is
vestigial and removing it is its own job. They exist so the number cannot grow
without someone writing down why.
"""

from __future__ import annotations

import json

import pytest

from apex.config.config_audit import audit, dropped_settings
from apex.config.parameters_cmd import read_params

# Settings that vanish between the key map and the namespace. Generated by
# building a config that sets every mapped key, so the list is complete and
# deterministic rather than whatever one workspace happened to contain.
CMD_DROPPED = {
    # Aperture-correction scale *optimiser*: the search was never implemented,
    # only the fixed small/large pair it would have searched between.
    "apcorr_large_scale_max", "apcorr_large_scale_min", "apcorr_max_pairs",
    "apcorr_min_gap_fwhm", "apcorr_optimize_scales", "apcorr_small_scale_max",
    "apcorr_small_scale_min",
    # Master catalogue: the code sizes it with `ref_cat_max_sources` instead.
    "N_master", "master_filter_keep", "master_flux_quantile",
    "master_iso_min_sep_pix", "master_keep_max",
    # Step 10 colour terms.
    "color_clip_sigma", "color_fit_iters", "color_slope_absmax",
    # Frame QC gate.
    "gate_nsrc_min", "gate_sky_sigma_max_e", "keep_positions_if_qc_fail",
    # Legacy duplicates of keys that do arrive: target.ra_deg lands on
    # `target_ra_deg`, which is what the code reads.
    "ra_deg", "dec_deg",
    # Named nowhere but the map and the unused pydantic schema — dead keys, not
    # disconnected ones. Removing them is a separate decision.
    "clip_max_adu", "clip_min_adu",
    # Miscellaneous vestiges.
    "cmd_max_sources", "save_src2ref_tforms", "ui_canvas_px",
    "wcs_match_radius_arcsec",
}

LC_DROPPED = {
    # Shared with CMD.
    "N_master", "clip_max_adu", "clip_min_adu", "dec_deg", "gate_nsrc_min",
    "gate_sky_sigma_max_e", "keep_positions_if_qc_fail", "master_filter_keep",
    "master_flux_quantile", "master_iso_min_sep_pix", "master_keep_max",
    "ra_deg", "save_src2ref_tforms", "ui_canvas_px", "wcs_match_radius_arcsec",
    "apcorr_scale_max", "apcorr_scale_min", "bkg2d_enable",
    "phot_use_original_frames",
    # LC-only gap: CMD reads these and LC does not, so the shared WCS solver
    # and Step 8 run to different numbers depending on which mode opened the
    # workspace. Every config on disk asks for values the LC literals do not
    # match — min_match_n 50 vs 20, min_match_rate 0.05 vs 0.20, max_p99_px
    # 5.2 vs 5.0, match_radius 2.5 vs 2.0 — so wiring them changes which frames
    # pass LC's QC. That is a science decision, not a plumbing fix.
    "wcs_qc_match_radius_arcsec", "wcs_qc_max_p99_px", "wcs_qc_min_match_n",
    "wcs_qc_min_match_rate",
    "idmatch_use_qc_pass_only", "idmatch_use_wcs_qc_gate",
    "idmatch_wcs_qc_max_p99_px", "idmatch_wcs_qc_max_rms_px",
    "idmatch_wcs_qc_min_inlier_rate", "idmatch_wcs_qc_min_match_n",
    "idmatch_wcs_qc_min_match_rate",
    # Same shape for Step 8: the knobs whose defaults were settled on 2026-08-16
    # reach CMD and not LC.
    "psf_final_pass_max_iter", "psf_forced_position_lock",
    "psf_grouper_budget_cap", "psf_grouper_budget_frac", "psf_interp_order",
    "psf_profile_error_frac",
}

# A workspace with the sections a real cluster run touches, written out rather
# than pointed at E:\ so the test runs anywhere.
WORKSPACE = {
    "io": {"result_dir": ".", "data_dir": "."},
    "instrument": {
        "telescope_focal_mm": 1048.0,
        "camera_pixel_um": 3.76,
        "binning": 1,
        "gain_e_per_adu": 0.689,
        "rdnoise_e": 2.1,
    },
    "photometry": {
        "apcorr": {"small_scale": 0.8, "large_scale": 2.4},
        "radii": {"sigma_clip": 3.0, "max_iter": 5},
    },
}


def _config_setting_every_mapped_key(key_map) -> dict:
    """A config that names every key the map knows, so nothing hides."""
    cfg = {"io": {"result_dir": ".", "data_dir": "."}}
    for row in key_map:
        path = tuple(row[0])
        node = cfg
        for part in path[:-1]:
            node = node.setdefault(part, {})
            if not isinstance(node, dict):
                break
        else:
            node.setdefault(path[-1], 1)
    return cfg


@pytest.fixture
def workspace(tmp_path):
    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(WORKSPACE), encoding="utf-8")
    return config


def test_the_instrument_geometry_arrives(workspace):
    """The pixel scale is derived from these two, so they have to be on `P`."""
    P = read_params(workspace).P
    assert P.telescope_focal_mm == pytest.approx(1048.0)
    assert P.camera_pixel_um == pytest.approx(3.76)


def test_the_pixel_scale_follows_the_configured_optics(workspace):
    """The defect itself: a non-default telescope must not land on the default
    plate scale. 206.265 * 3.76 / 1048 = 0.740 "/px, not 0.197."""
    from apex.core.instrument import InstrumentConfig

    params = read_params(workspace)
    assert InstrumentConfig(params).pix_scale_bin == pytest.approx(0.740, abs=1e-3)


def test_the_aperture_scales_arrive(workspace):
    P = read_params(workspace).P
    assert P.apcorr_small_scale == pytest.approx(0.8)
    assert P.apcorr_large_scale == pytest.approx(2.4)


def test_a_workspace_of_real_settings_loses_nothing(workspace):
    assert dropped_settings(read_params(workspace).P) == []


@pytest.mark.parametrize("mode,pinned", [("cmd", CMD_DROPPED), ("lc", LC_DROPPED)])
def test_the_set_of_settings_that_go_nowhere_is_the_pinned_one(mode, pinned, tmp_path):
    """Set every mapped key and check exactly which ones fail to arrive.

    A name appearing here that is not pinned is a new silent setting: add the
    keyword to the namespace constructor, or drop the key from the map if it is
    really dead — and either way say which in `docs/audit/CONFIG_REACHABILITY.md`.
    """
    if mode == "lc":
        from apex.config.parameters_lc import TOML_KEY_MAP, read_params as read
    else:
        from apex.config.parameters_cmd import TOML_KEY_MAP, read_params as read

    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(_config_setting_every_mapped_key(TOML_KEY_MAP)),
                      encoding="utf-8")
    lost = set(dropped_settings(read(config).P))
    assert not (lost - pinned), f"새로 사라지는 설정: {sorted(lost - pinned)}"
    assert not (pinned - lost), f"이제 도착한다 — 목록에서 지울 것: {sorted(pinned - lost)}"


def test_the_step7_cache_notices_an_aperture_change(tmp_path):
    """The signature listed `forced_r_ap_scale`, a name nothing set, so every
    run hashed None for it and a changed aperture reused the old cache."""
    import re
    from pathlib import Path

    source = (Path(__file__).absolute().parents[1]
              / "apex/gui/workflow/step7_forced_aperture_phot.py").read_text(encoding="utf-8")
    block = source[source.index("_FORCED_SIGNATURE_PARAMS = ("):]
    block = block[:block.index("\n)")]
    names = re.findall(r'"([a-z_0-9]+)"', block)
    assert "apcorr_small_scale" in names
    assert "apcorr_large_scale" in names
    assert "annulus_sigma_clip" in names
    assert "fitsky_max_iter" in names

    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps(WORKSPACE), encoding="utf-8")
    P = read_params(config).P
    # `ref_cat_*` are defined in LC only; nothing sets them, so they cannot go
    # stale, but they are the remaining hole in this signature.
    absent = [n for n in names if not hasattr(P, n)]
    assert all(n.startswith("ref_cat_") for n in absent), absent


def test_the_audit_reports_both_kinds(workspace):
    result = audit(workspace)
    assert set(result) == {"unmapped", "dropped"}
    assert not [name for name in result["unmapped"] if name.startswith("photometry.")]


def test_turning_the_aperture_correction_off_does_something(workspace):
    """`photometry.apcorr.apply` reached `P` and nothing read it — Step 7
    multiplied by apcorr unconditionally. Every workspace has it true, so
    wiring it changed no stored product, but the switch has to work."""
    from pathlib import Path

    P = read_params(workspace).P
    assert P.apcorr_apply is True

    source = (Path(__file__).absolute().parents[1]
              / "apex/analysis/forced_photometry.py").read_text(encoding="utf-8")
    assert 'getattr(P, "apcorr_apply"' in source
    assert "if apcorr_apply and n_gc_stars >= apcorr_min_n:" in source

    signature = (Path(__file__).absolute().parents[1]
                 / "apex/gui/workflow/step7_forced_aperture_phot.py").read_text(encoding="utf-8")
    block = signature[signature.index("_FORCED_SIGNATURE_PARAMS = ("):]
    assert '"apcorr_apply"' in block[:block.index("\n)")]


# ---------------------------------------------------------------------------
# The map row is the whole definition of a setting (2026-08-16).
#
# Before, a setting was written twice: a row in `parameter_map` saying where it
# comes from and what it is called, and a keyword in a 452-line
# `SimpleNamespace(...)` call saying what type it is and what it defaults to.
# Nothing checked that the two lists agreed, and for 74 settings they did not.
# Now a four-part row carries all four facts and the namespace is built from the
# rows, so a setting cannot be half-added.


def test_a_four_part_row_arrives_with_its_type_and_default(tmp_path):
    from apex.config.parameter_map import CMD_TOML_KEY_MAP

    config = tmp_path / "apex_config.json"
    config.write_text(json.dumps({"io": {"result_dir": ".", "data_dir": "."}}),
                      encoding="utf-8")
    P = read_params(config).P
    built = [row for row in CMD_TOML_KEY_MAP if len(row) >= 4]
    assert len(built) > 250, "맵이 대부분의 설정을 직접 세워야 한다"
    missing = [row[1] for row in built if not hasattr(P, row[1])]
    assert not missing, f"맵이 세운다고 한 설정이 도착하지 않았다: {missing}"


def test_the_default_in_the_row_is_the_value_when_the_file_is_silent():
    """A silent file has to give back exactly what the row says.

    Checked against `build_settings` rather than the finished namespace: a
    loader may override a shared row on purpose — CMD asks for
    `wcs_qc_max_rms_px` 3.5 where the row carries LC's 2.5 — and that override
    is the documented way to say "this one differs per mode".
    """
    import math

    from apex.config.parameter_map import CMD_TOML_KEY_MAP, build_settings

    values = build_settings({}, CMD_TOML_KEY_MAP)
    for row in CMD_TOML_KEY_MAP:
        if len(row) < 4:
            continue
        got, want = values[row[1]], row[3]
        if isinstance(want, float) and math.isnan(want):
            assert isinstance(got, float) and math.isnan(got), row[1]
            continue
        assert got == want, row[1]


def test_the_type_survives_a_string_the_way_the_old_helpers_did():
    """Legacy TOML wrote numbers and booleans as text and migrated workspaces
    still carry them, so the coercion has to keep accepting strings — and has
    to keep rejecting a boolean in a numeric field rather than reading it as 1."""
    from apex.config.parameter_map import coerce_setting

    assert coerce_setting("float", "2.5", 0.0) == 2.5
    assert coerce_setting("int", "7.9", 0) == 7
    assert coerce_setting("bool", "yes", False) is True
    assert coerce_setting("bool", "nonsense", True) is False   # _as_bool, not default
    assert coerce_setting("float", True, 3947.0) == 3947.0     # str(True) is not a float
    assert coerce_setting("float", None, 3947.0) == 3947.0
    assert coerce_setting("float_or_none", "", 1.0) is None
    assert coerce_setting("str", None, "cache") == "cache"


def test_the_key_map_is_not_copied_anywhere():
    """Both loaders used to define a second `TOML_KEY_MAP` and overwrite it on
    the next line. Editing that copy did nothing, and by the time it went it was
    missing 81 rows in CMD and 123 in LC."""
    from pathlib import Path

    repo = Path(__file__).absolute().parents[1]
    for module in ("apex/config/parameters_cmd.py", "apex/config/parameters_lc.py"):
        source = (repo / module).read_text(encoding="utf-8")
        assert "TOML_KEY_MAP: list[" not in source, f"{module} 이 맵을 다시 정의한다"
