"""Assemble the APEX validation figure set into a paper-ready index + overview.

Consumes whatever is currently in validation/paper/figures/ and
validation/paper/captions/ and produces:

  * validation/paper/FIGURES.md  — an index embedding each figure (PNG) with its
    caption, for the docs site / paper draft.
  * validation/paper/figures/overview_contact_sheet.png — a single contact sheet
    (all four figures stacked) for a one-glance overview.

Run after all figNN_*.py have produced their outputs. Idempotent.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

REPO = Path(r"C:\Users\bmffr\Desktop\Result\Automated_Photometry_EXtraction")
PAPER = REPO / "validation" / "paper"
FIG = PAPER / "figures"
CAP = PAPER / "captions"

FIGURES = [
    ("fig1_completeness", "Completeness function & 50% depth"),
    ("fig2_error_model", "Photometric error-model validation (pull distribution)"),
    ("fig3_parameter_sweep", "Parameter & observing-condition sensitivity"),
    ("fig4_crosscheck_sep", "Independent cross-check against sep (synthetic truth)"),
    ("fig5_crosscheck_iraf", "External cross-check against IRAF/DAOPHOT (real NGC 457 data)"),
]


def build_index() -> Path:
    lines: list[str] = [
        "# APEX Validation Figures",
        "",
        "Publication-quality validation figure set for APEX (aperture/PSF photometry "
        "pipeline). Each figure is generated by its `figNN_*.py` script from a "
        "reproducible, self-contained artificial-star experiment (no external data). "
        "Vector PDFs live next to the PNGs for LaTeX inclusion.",
        "",
    ]
    for i, (stem, title) in enumerate(FIGURES, start=1):
        png = FIG / f"{stem}.png"
        pdf = FIG / f"{stem}.pdf"
        cap_path = CAP / f"{stem}.md"
        lines.append(f"## Figure {i} — {title}")
        lines.append("")
        if png.exists():
            lines.append(f"![Figure {i}](figures/{stem}.png)")
        else:
            lines.append(f"_(missing: figures/{stem}.png)_")
        lines.append("")
        if pdf.exists():
            lines.append(f"Vector: [`figures/{stem}.pdf`](figures/{stem}.pdf) · "
                         f"Script: [`{stem}.py`]({stem}.py)")
            lines.append("")
        if cap_path.exists():
            lines.append(cap_path.read_text(encoding="utf-8").strip())
            lines.append("")
    out = PAPER / "FIGURES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def build_contact_sheet() -> Path | None:
    pngs = [(FIG / f"{stem}.png", f"Figure {i}") for i, (stem, _) in enumerate(FIGURES, 1)]
    pngs = [(p, label) for p, label in pngs if p.exists()]
    if not pngs:
        return None
    # One row per figure; height proportional to each image's aspect ratio.
    imgs = [(mpimg.imread(p), label) for p, label in pngs]
    ratios = [img.shape[0] / img.shape[1] for img, _ in imgs]  # h/w
    width_in = 7.0
    heights = [width_in * r for r in ratios]
    fig = plt.figure(figsize=(width_in, sum(heights) + 0.4 * len(imgs)))
    gs = fig.add_gridspec(len(imgs), 1, height_ratios=heights, hspace=0.12)
    for ax_i, (img, label) in enumerate(imgs):
        ax = fig.add_subplot(gs[ax_i, 0])
        ax.imshow(img)
        ax.set_axis_off()
        ax.set_title(label, fontsize=10, loc="left")
    out = FIG / "overview_contact_sheet.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return out


def main() -> int:
    idx = build_index()
    print(f"index: {idx}")
    sheet = build_contact_sheet()
    print(f"contact sheet: {sheet}")
    missing = [stem for stem, _ in FIGURES if not (FIG / f"{stem}.png").exists()]
    if missing:
        print(f"WARNING missing figures: {missing}")
        return 1
    print(f"all {len(FIGURES)} figures present.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
